export_languages:
  - ar
  - ca
  - da
  - es-ES
  - nl
  - fi
  - fr
  - de
  - he
  - it
  - nb
  - pl
  - ru
  - sv-SE
  - tr
  - uk
  - zh-CN
  - pt-PT
  - pt-BR
  - sk
  - vi
  - hu
files:
  - source: /Localizations/Main/en.lproj/Localizable.strings
    translation: /Localizations/Main/%osx_locale%.lproj/Localizable.strings
